//====== Copyright © Sandern Corporation, All rights reserved. ===========//
//
// Purpose:	
//
//=============================================================================//

#ifndef RECAST_OFFMESH_CONNECTION_H
#define RECAST_OFFMESH_CONNECTION_H

#pragma once

#include "baseentity.h"
#include "recast/recast_imgr.h"

enum RecastOfffMeshConnSF_t : unsigned short
{
	SF_OFFMESHCONN_NONE = 0,

	SF_OFFMESHCONN_JUMPEDGE = (1 << 0),

	SF_OFFMESHCONN_TYPE_FLAGS_START = (1 << 1),

	SF_OFFMESHCONN_TYPE_HUMAN = (SF_OFFMESHCONN_TYPE_FLAGS_START << RECAST_NAVMESH_HUMAN),
	SF_OFFMESHCONN_TYPE_SMALL_CENTERED = (SF_OFFMESHCONN_TYPE_FLAGS_START << RECAST_NAVMESH_SMALL_CENTERED),
	SF_OFFMESHCONN_TYPE_WIDE_HUMAN = (SF_OFFMESHCONN_TYPE_FLAGS_START << RECAST_NAVMESH_WIDE_HUMAN),
	SF_OFFMESHCONN_TYPE_TINY = (SF_OFFMESHCONN_TYPE_FLAGS_START << RECAST_NAVMESH_TINY),
	SF_OFFMESHCONN_TYPE_WIDE_SHORT = (SF_OFFMESHCONN_TYPE_FLAGS_START << RECAST_NAVMESH_WIDE_SHORT),
	SF_OFFMESHCONN_TYPE_MEDIUM = (SF_OFFMESHCONN_TYPE_FLAGS_START << RECAST_NAVMESH_MEDIUM),
	SF_OFFMESHCONN_TYPE_TINY_CENTERED = (SF_OFFMESHCONN_TYPE_FLAGS_START << RECAST_NAVMESH_TINY_CENTERED),
	SF_OFFMESHCONN_TYPE_LARGE = (SF_OFFMESHCONN_TYPE_FLAGS_START << RECAST_NAVMESH_LARGE),
	SF_OFFMESHCONN_TYPE_LARGE_CENTERED = (SF_OFFMESHCONN_TYPE_FLAGS_START << RECAST_NAVMESH_LARGE_CENTERED),
	SF_OFFMESHCONN_TYPE_MEDIUM_TALL = (SF_OFFMESHCONN_TYPE_FLAGS_START << RECAST_NAVMESH_MEDIUM_TALL),
	SF_OFFMESHCONN_TYPE_TINY_FLUID = (SF_OFFMESHCONN_TYPE_FLAGS_START << RECAST_NAVMESH_TINY_FLUID),
	SF_OFFMESHCONN_TYPE_MEDIUMBIG = (SF_OFFMESHCONN_TYPE_FLAGS_START << RECAST_NAVMESH_MEDIUMBIG),
	SF_OFFMESHCONN_TYPE_PLAYER = (SF_OFFMESHCONN_TYPE_FLAGS_START << RECAST_NAVMESH_PLAYER),
};

FLAGENUM_OPERATORS( RecastOfffMeshConnSF_t, unsigned short )

//-----------------------------------------------------------------------------
// 
//-----------------------------------------------------------------------------
class COffMeshConnection : public CServerOnlyPointEntity
{
public:
	DECLARE_CLASS( COffMeshConnection, CServerOnlyPointEntity );

	DECLARE_SPAWNFLAGS( RecastOfffMeshConnSF_t )
};

#endif // RECAST_OFFMESH_CONNECTION_H