#ifndef LINUX_HAMMER_IPC_H
#define LINUX_HAMMER_IPC_H

#pragma once

#define LINUX_HAMMER_IPC_QUIT     0
#define LINUX_HAMMER_IPC_FIND_WND 1
#define LINUX_HAMMER_IPC_SEND_CMD 2

#define LINUX_HAMMER_IPC_RET_SUCCESS      0
#define LINUX_HAMMER_IPC_RET_FAIL         1
#define LINUX_HAMMER_IPC_RET_NOT_RUNNING  2
#define LINUX_HAMMER_IPC_RET_UNKNOWN_CODE 3

#endif
